// This single route handles all 5 export formats — JSON, CSV, XML, Markdown, and PDF.
import connectDB from '@/lib/mongodb';
import Weather from '@/models/Weather';
import { NextResponse } from 'next/server';

export async function GET(request) {
  const { searchParams } = new URL(request.url);
  const format = searchParams.get('format');

  try {
    await connectDB();
    const records = await Weather.find().sort({ createdAt: -1 });

    if (format === 'json') {
      if (records.length === 0) {
        return new NextResponse(JSON.stringify([], null, 2), {
          headers: {
            'Content-Type': 'application/json',
            'Content-Disposition': 'attachment; filename=weather-data.json',
          },
        });
      }
      const cleaned = records.map((r) => ({
        location: r.location,
        startDate: r.dateRange.start,
        endDate: r.dateRange.end,
        temperature: `${Math.round(r.temperature)}°C`,
        description: r.description,
        humidity: `${r.humidity}%`,
        windSpeed: `${r.windSpeed} m/s`,
      }));
      return new NextResponse(JSON.stringify(cleaned, null, 2), {
        headers: {
          'Content-Type': 'application/json',
          'Content-Disposition': 'attachment; filename=weather-data.json',
        },
      });
    }

    if (format === 'csv') {
      const headers = 'Location,Start Date,End Date,Temperature,Description,Humidity,Wind Speed\n';
      const rows = records.length === 0
        ? 'No records found.'
        : records.map((r) =>
            `${r.location},${r.dateRange.start},${r.dateRange.end},${Math.round(r.temperature)}°C,${r.description},${r.humidity}%,${r.windSpeed} m/s`
          ).join('\n');
      return new NextResponse(headers + rows, {
        headers: {
          'Content-Type': 'text/csv',
          'Content-Disposition': 'attachment; filename=weather-data.csv',
        },
      });
    }

    if (format === 'pdf') {
      const { jsPDF } = await import('jspdf');
      const doc = new jsPDF();

      doc.setFontSize(20);
      doc.setFont('helvetica', 'bold');
      doc.text('Weather Records', 14, 20);

      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(100);
      doc.text(`Exported on ${new Date().toLocaleDateString('en-US')}`, 14, 28);

      const headers = ['Location', 'Start Date', 'End Date', 'Temp', 'Description', 'Humidity', 'Wind'];
      const colWidths = [30, 28, 28, 18, 40, 22, 22];
      let startX = 14;
      let y = 40;

      doc.setFillColor(30, 30, 30);
      doc.rect(14, y - 6, 182, 8, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(8);
      doc.setFont('helvetica', 'bold');

      headers.forEach((header, i) => {
        doc.text(header, startX, y);
        startX += colWidths[i];
      });

      y += 6;

      if (records.length === 0) {
        doc.setTextColor(100);
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(9);
        doc.text('No records found.', 14, y + 6);
      } else {
        records.forEach((r, index) => {
          if (y > 270) {
            doc.addPage();
            y = 20;
          }

          const isEven = index % 2 === 0;
          doc.setFillColor(isEven ? 245 : 255, isEven ? 245 : 255, isEven ? 245 : 255);
          doc.rect(14, y - 5, 182, 7, 'F');

          doc.setTextColor(30, 30, 30);
          doc.setFont('helvetica', 'normal');
          doc.setFontSize(8);

          const row = [
            r.location,
            r.dateRange.start,
            r.dateRange.end,
            `${Math.round(r.temperature)}\u00B0C`,
            r.description,
            `${r.humidity}%`,
            `${r.windSpeed} m/s`,
          ];

          startX = 14;
          row.forEach((cell, i) => {
            const text = String(cell);
            const maxChars = Math.floor(colWidths[i] / 2);
            const truncated = text.length > maxChars ? text.substring(0, maxChars) + '...' : text;
            doc.text(truncated, startX, y);
            startX += colWidths[i];
          });

          y += 7;
        });
      }

      doc.setTextColor(150);
      doc.setFontSize(8);
      doc.text('Generated by Weather App — Mohamed Dhia Abidi', 14, 285);

      const pdfBuffer = Buffer.from(doc.output('arraybuffer'));

      return new NextResponse(pdfBuffer, {
        headers: {
          'Content-Type': 'application/pdf',
          'Content-Disposition': 'attachment; filename=weather-data.pdf',
        },
      });
    }

    if (format === 'xml') {
      const xml = records.length === 0
        ? `<?xml version="1.0" encoding="UTF-8"?>\n<records>\n  <message>No records found.</message>\n</records>`
        : `<?xml version="1.0" encoding="UTF-8"?>
<records>
${records.map((r) => `  <record>
    <location>${r.location}</location>
    <startDate>${r.dateRange.start}</startDate>
    <endDate>${r.dateRange.end}</endDate>
    <temperature>${Math.round(r.temperature)}°C</temperature>
    <description>${r.description}</description>
    <humidity>${r.humidity}%</humidity>
    <windSpeed>${r.windSpeed} m/s</windSpeed>
  </record>`).join('\n')}
</records>`;
      return new NextResponse(xml, {
        headers: {
          'Content-Type': 'application/xml',
          'Content-Disposition': 'attachment; filename=weather-data.xml',
        },
      });
    }

    if (format === 'markdown') {
      const md = records.length === 0
        ? `# Weather Records\n\nNo records found.`
        : `# Weather Records\n\n` +
          `| Location | Start Date | End Date | Temperature | Description | Humidity | Wind Speed |\n` +
          `|----------|------------|----------|-------------|-------------|----------|------------|\n` +
          records.map((r) =>
            `| ${r.location} | ${r.dateRange.start} | ${r.dateRange.end} | ${Math.round(r.temperature)}°C | ${r.description} | ${r.humidity}% | ${r.windSpeed} m/s |`
          ).join('\n');
      return new NextResponse(md, {
        headers: {
          'Content-Type': 'text/markdown',
          'Content-Disposition': 'attachment; filename=weather-data.md',
        },
      });
    }

    return NextResponse.json({ error: 'Invalid format' }, { status: 400 });
  } catch (error) {
    return NextResponse.json({ error: 'Failed to export data' }, { status: 500 });
  }
}
